language: node_js
node_js:
  - "8"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ldap-utils
      - slapd
      - libldap2-dev

script: 
  sudo service slapd stop
  sleep 3
  sudo slapadd -l ./backup.ldif
  sleep 3
  sudo service slapd restart
  sleep 3
  ldapsearch -D cn=admin,dc=demoApp,dc=com -w secret -b dc=demoApp,dc=com
