language: node_js
node_js:
  - "8"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ldap-utils
      - slapd
      - libldap2-dev

before_script:
  - sudo mkdir /etc/slapd.d
  - sudo mv ./slapd.d/* /etc/slapd.d/
  - sleep 3
  - sudo slappasswd -s secret
  - sudo slapcat
  - sleep 3
  - ldapadd -H ldap://localhost:389 -D cn=admin,dc=demoApp,dc=com -w secret -f ./light_db.ldif