language: node_js
node_js:
  - "8"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ldap-utils
      - slapd
      - libldap2-dev

before_script:
  - sudo mkdir /usr/local/var/openldap-data -p
  -   slapadd -n 0 -F /usr/local/etc/slapd.d -l ./slapd.ldif
  -   slapd -F /usr/local/etc/slapd.d
  - ldapadd -D cn=admin,dc=demoApp,dc=com -w secret ./backup.ldif