language: node_js
node_js:
  - "8"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ldap-utils
      - slapd
      - libldap2-dev

before_script:
  - sudo mkdir /tmp/slapd.d
  - sudo slapd -f ./test/ldifs/slapd.conf
  - sleep 3
  - ldapadd -D cn=admin,dc=demoApp,dc=com -w test -f ./light_db.ldif