language: node_js
node_js:
  - "8"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ldap-utils
      - slapd
      - libldap2-dev

before_script:
  #- ls  /etc/ldap/slapd.d/
  - sudo mkdir /usr/local/var/openldap-data -p &
  - sleep 2
  - sudo slapcat -n0
  - sudo service slapd stop &
  - sudo slapadd -n 0 -F /etc/ldap/slapd.d  -l ./settings.ldif &
  - sleep 2
  - sudo service slapd start &
  - slapd -F /etc/ldap/slapd.d &
  - sleep 2 &
  - ldapadd -D cn=admin,dc=demoApp,dc=com -w secret -f ./backup.ldif