language: node_js
node_js:
  - "8"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ldap-utils
      - slapd
      - libldap2-dev

before_script:
  - sudo mkdir /usr/local/var/openldap-data -p 
  - sudo service slapd stop 
  - sudo rm -R /etc/ldap/slapd.d/
  - sudo mkdir /etc/ldap/slapd.d/
  - sudo slapadd -n 0 -F /etc/ldap/slapd.d/  -l ./settings.ldif
  - sudo chmod 777 -R /etc/ldap/
  - sudo service slapd restart
  - sudo service slapd status
  - sudo slapcat
